// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetAccountBalance_FullMethodName    = "/proto.AdminService/GetAccountBalance"
	AdminService_InitiatePayment_FullMethodName      = "/proto.AdminService/InitiatePayment"
	AdminService_RequestCertificate_FullMethodName   = "/proto.AdminService/RequestCertificate"
	AdminService_UpdateStudentProfile_FullMethodName = "/proto.AdminService/UpdateStudentProfile"
	AdminService_GetFinanceHistory_FullMethodName    = "/proto.AdminService/GetFinanceHistory"
	AdminService_GetDormitoryInfo_FullMethodName     = "/proto.AdminService/GetDormitoryInfo"
	AdminService_RequestDormRepair_FullMethodName    = "/proto.AdminService/RequestDormRepair"
	AdminService_GetScholarshipInfo_FullMethodName   = "/proto.AdminService/GetScholarshipInfo"
	AdminService_GetLibraryDebts_FullMethodName      = "/proto.AdminService/GetLibraryDebts"
	AdminService_ReserveLibraryBook_FullMethodName   = "/proto.AdminService/ReserveLibraryBook"
	AdminService_GetDocumentStatus_FullMethodName    = "/proto.AdminService/GetDocumentStatus"
	AdminService_GetLaundryStatus_FullMethodName     = "/proto.AdminService/GetLaundryStatus"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetAccountBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	RequestCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	UpdateStudentProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileUpdateResponse, error)
	GetFinanceHistory(ctx context.Context, in *FinanceHistoryRequest, opts ...grpc.CallOption) (*FinanceHistoryResponse, error)
	GetDormitoryInfo(ctx context.Context, in *DormitoryRequest, opts ...grpc.CallOption) (*DormitoryResponse, error)
	RequestDormRepair(ctx context.Context, in *RepairRequest, opts ...grpc.CallOption) (*RepairResponse, error)
	GetScholarshipInfo(ctx context.Context, in *ScholarshipRequest, opts ...grpc.CallOption) (*ScholarshipResponse, error)
	GetLibraryDebts(ctx context.Context, in *LibraryDebtsRequest, opts ...grpc.CallOption) (*LibraryDebtsResponse, error)
	ReserveLibraryBook(ctx context.Context, in *ReserveBookRequest, opts ...grpc.CallOption) (*ReserveBookResponse, error)
	GetDocumentStatus(ctx context.Context, in *DocStatusRequest, opts ...grpc.CallOption) (*DocStatusResponse, error)
	GetLaundryStatus(ctx context.Context, in *LaundryRequest, opts ...grpc.CallOption) (*LaundryResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetAccountBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, AdminService_GetAccountBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, AdminService_InitiatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RequestCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, AdminService_RequestCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateStudentProfile(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*ProfileUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileUpdateResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateStudentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetFinanceHistory(ctx context.Context, in *FinanceHistoryRequest, opts ...grpc.CallOption) (*FinanceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinanceHistoryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetFinanceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDormitoryInfo(ctx context.Context, in *DormitoryRequest, opts ...grpc.CallOption) (*DormitoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DormitoryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDormitoryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RequestDormRepair(ctx context.Context, in *RepairRequest, opts ...grpc.CallOption) (*RepairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepairResponse)
	err := c.cc.Invoke(ctx, AdminService_RequestDormRepair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetScholarshipInfo(ctx context.Context, in *ScholarshipRequest, opts ...grpc.CallOption) (*ScholarshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScholarshipResponse)
	err := c.cc.Invoke(ctx, AdminService_GetScholarshipInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLibraryDebts(ctx context.Context, in *LibraryDebtsRequest, opts ...grpc.CallOption) (*LibraryDebtsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LibraryDebtsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetLibraryDebts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ReserveLibraryBook(ctx context.Context, in *ReserveBookRequest, opts ...grpc.CallOption) (*ReserveBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveBookResponse)
	err := c.cc.Invoke(ctx, AdminService_ReserveLibraryBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDocumentStatus(ctx context.Context, in *DocStatusRequest, opts ...grpc.CallOption) (*DocStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDocumentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLaundryStatus(ctx context.Context, in *LaundryRequest, opts ...grpc.CallOption) (*LaundryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaundryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetLaundryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	GetAccountBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	InitiatePayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	RequestCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error)
	UpdateStudentProfile(context.Context, *ProfileUpdateRequest) (*ProfileUpdateResponse, error)
	GetFinanceHistory(context.Context, *FinanceHistoryRequest) (*FinanceHistoryResponse, error)
	GetDormitoryInfo(context.Context, *DormitoryRequest) (*DormitoryResponse, error)
	RequestDormRepair(context.Context, *RepairRequest) (*RepairResponse, error)
	GetScholarshipInfo(context.Context, *ScholarshipRequest) (*ScholarshipResponse, error)
	GetLibraryDebts(context.Context, *LibraryDebtsRequest) (*LibraryDebtsResponse, error)
	ReserveLibraryBook(context.Context, *ReserveBookRequest) (*ReserveBookResponse, error)
	GetDocumentStatus(context.Context, *DocStatusRequest) (*DocStatusResponse, error)
	GetLaundryStatus(context.Context, *LaundryRequest) (*LaundryResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetAccountBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountBalance not implemented")
}
func (UnimplementedAdminServiceServer) InitiatePayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (UnimplementedAdminServiceServer) RequestCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedAdminServiceServer) UpdateStudentProfile(context.Context, *ProfileUpdateRequest) (*ProfileUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStudentProfile not implemented")
}
func (UnimplementedAdminServiceServer) GetFinanceHistory(context.Context, *FinanceHistoryRequest) (*FinanceHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFinanceHistory not implemented")
}
func (UnimplementedAdminServiceServer) GetDormitoryInfo(context.Context, *DormitoryRequest) (*DormitoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDormitoryInfo not implemented")
}
func (UnimplementedAdminServiceServer) RequestDormRepair(context.Context, *RepairRequest) (*RepairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestDormRepair not implemented")
}
func (UnimplementedAdminServiceServer) GetScholarshipInfo(context.Context, *ScholarshipRequest) (*ScholarshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScholarshipInfo not implemented")
}
func (UnimplementedAdminServiceServer) GetLibraryDebts(context.Context, *LibraryDebtsRequest) (*LibraryDebtsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLibraryDebts not implemented")
}
func (UnimplementedAdminServiceServer) ReserveLibraryBook(context.Context, *ReserveBookRequest) (*ReserveBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveLibraryBook not implemented")
}
func (UnimplementedAdminServiceServer) GetDocumentStatus(context.Context, *DocStatusRequest) (*DocStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetLaundryStatus(context.Context, *LaundryRequest) (*LaundryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLaundryStatus not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetAccountBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetAccountBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_InitiatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).InitiatePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RequestCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RequestCertificate(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateStudentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateStudentProfile(ctx, req.(*ProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetFinanceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinanceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetFinanceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetFinanceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetFinanceHistory(ctx, req.(*FinanceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDormitoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DormitoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDormitoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDormitoryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDormitoryInfo(ctx, req.(*DormitoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RequestDormRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RequestDormRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RequestDormRepair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RequestDormRepair(ctx, req.(*RepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetScholarshipInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScholarshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetScholarshipInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetScholarshipInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetScholarshipInfo(ctx, req.(*ScholarshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLibraryDebts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LibraryDebtsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLibraryDebts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLibraryDebts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLibraryDebts(ctx, req.(*LibraryDebtsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ReserveLibraryBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReserveLibraryBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ReserveLibraryBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReserveLibraryBook(ctx, req.(*ReserveBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDocumentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDocumentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDocumentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDocumentStatus(ctx, req.(*DocStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLaundryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaundryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLaundryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLaundryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLaundryStatus(ctx, req.(*LaundryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountBalance",
			Handler:    _AdminService_GetAccountBalance_Handler,
		},
		{
			MethodName: "InitiatePayment",
			Handler:    _AdminService_InitiatePayment_Handler,
		},
		{
			MethodName: "RequestCertificate",
			Handler:    _AdminService_RequestCertificate_Handler,
		},
		{
			MethodName: "UpdateStudentProfile",
			Handler:    _AdminService_UpdateStudentProfile_Handler,
		},
		{
			MethodName: "GetFinanceHistory",
			Handler:    _AdminService_GetFinanceHistory_Handler,
		},
		{
			MethodName: "GetDormitoryInfo",
			Handler:    _AdminService_GetDormitoryInfo_Handler,
		},
		{
			MethodName: "RequestDormRepair",
			Handler:    _AdminService_RequestDormRepair_Handler,
		},
		{
			MethodName: "GetScholarshipInfo",
			Handler:    _AdminService_GetScholarshipInfo_Handler,
		},
		{
			MethodName: "GetLibraryDebts",
			Handler:    _AdminService_GetLibraryDebts_Handler,
		},
		{
			MethodName: "ReserveLibraryBook",
			Handler:    _AdminService_ReserveLibraryBook_Handler,
		},
		{
			MethodName: "GetDocumentStatus",
			Handler:    _AdminService_GetDocumentStatus_Handler,
		},
		{
			MethodName: "GetLaundryStatus",
			Handler:    _AdminService_GetLaundryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}
