// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float32                `protobuf:"fixed32,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	DocType       string                 `protobuf:"bytes,2,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CertificateRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CertificateRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CertificateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CertificateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProfileUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateRequest) Reset() {
	*x = ProfileUpdateRequest{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateRequest) ProtoMessage() {}

func (x *ProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileUpdateRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ProfileUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileUpdateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ProfileUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateResponse) Reset() {
	*x = ProfileUpdateResponse{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateResponse) ProtoMessage() {}

func (x *ProfileUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProfileUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FinanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinanceHistoryRequest) Reset() {
	*x = FinanceHistoryRequest{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinanceHistoryRequest) ProtoMessage() {}

func (x *FinanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*FinanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *FinanceHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TransactionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionItem) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionItem) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *TransactionItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type FinanceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionItem     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinanceHistoryResponse) Reset() {
	*x = FinanceHistoryResponse{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinanceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinanceHistoryResponse) ProtoMessage() {}

func (x *FinanceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinanceHistoryResponse.ProtoReflect.Descriptor instead.
func (*FinanceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *FinanceHistoryResponse) GetTransactions() []*TransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type DormitoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DormitoryRequest) Reset() {
	*x = DormitoryRequest{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DormitoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DormitoryRequest) ProtoMessage() {}

func (x *DormitoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DormitoryRequest.ProtoReflect.Descriptor instead.
func (*DormitoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DormitoryRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type DormitoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Building      string                 `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	Floor         string                 `protobuf:"bytes,3,opt,name=floor,proto3" json:"floor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DormitoryResponse) Reset() {
	*x = DormitoryResponse{}
	mi := &file_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DormitoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DormitoryResponse) ProtoMessage() {}

func (x *DormitoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DormitoryResponse.ProtoReflect.Descriptor instead.
func (*DormitoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *DormitoryResponse) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *DormitoryResponse) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

func (x *DormitoryResponse) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

type RepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairRequest) Reset() {
	*x = RepairRequest{}
	mi := &file_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairRequest) ProtoMessage() {}

func (x *RepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairRequest.ProtoReflect.Descriptor instead.
func (*RepairRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RepairRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RepairRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RepairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairResponse) Reset() {
	*x = RepairResponse{}
	mi := &file_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairResponse) ProtoMessage() {}

func (x *RepairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairResponse.ProtoReflect.Descriptor instead.
func (*RepairResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RepairResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *RepairResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ScholarshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScholarshipRequest) Reset() {
	*x = ScholarshipRequest{}
	mi := &file_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScholarshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScholarshipRequest) ProtoMessage() {}

func (x *ScholarshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScholarshipRequest.ProtoReflect.Descriptor instead.
func (*ScholarshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ScholarshipRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ScholarshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	NextPayment   string                 `protobuf:"bytes,4,opt,name=next_payment,json=nextPayment,proto3" json:"next_payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScholarshipResponse) Reset() {
	*x = ScholarshipResponse{}
	mi := &file_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScholarshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScholarshipResponse) ProtoMessage() {}

func (x *ScholarshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScholarshipResponse.ProtoReflect.Descriptor instead.
func (*ScholarshipResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ScholarshipResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScholarshipResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScholarshipResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ScholarshipResponse) GetNextPayment() string {
	if x != nil {
		return x.NextPayment
	}
	return ""
}

type LibraryDebtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryDebtsRequest) Reset() {
	*x = LibraryDebtsRequest{}
	mi := &file_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryDebtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryDebtsRequest) ProtoMessage() {}

func (x *LibraryDebtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryDebtsRequest.ProtoReflect.Descriptor instead.
func (*LibraryDebtsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *LibraryDebtsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type LibraryDebtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []string               `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	Fine          float32                `protobuf:"fixed32,2,opt,name=fine,proto3" json:"fine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryDebtsResponse) Reset() {
	*x = LibraryDebtsResponse{}
	mi := &file_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryDebtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryDebtsResponse) ProtoMessage() {}

func (x *LibraryDebtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryDebtsResponse.ProtoReflect.Descriptor instead.
func (*LibraryDebtsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{18}
}

func (x *LibraryDebtsResponse) GetBooks() []string {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *LibraryDebtsResponse) GetFine() float32 {
	if x != nil {
		return x.Fine
	}
	return 0
}

type ReserveBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveBookRequest) Reset() {
	*x = ReserveBookRequest{}
	mi := &file_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBookRequest) ProtoMessage() {}

func (x *ReserveBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBookRequest.ProtoReflect.Descriptor instead.
func (*ReserveBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ReserveBookRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ReserveBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *ReserveBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReserveBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DueDate       string                 `protobuf:"bytes,2,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveBookResponse) Reset() {
	*x = ReserveBookResponse{}
	mi := &file_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBookResponse) ProtoMessage() {}

func (x *ReserveBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBookResponse.ProtoReflect.Descriptor instead.
func (*ReserveBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ReserveBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveBookResponse) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

type DocStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocStatusRequest) Reset() {
	*x = DocStatusRequest{}
	mi := &file_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocStatusRequest) ProtoMessage() {}

func (x *DocStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocStatusRequest.ProtoReflect.Descriptor instead.
func (*DocStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *DocStatusRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type DocItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocItem) Reset() {
	*x = DocItem{}
	mi := &file_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocItem) ProtoMessage() {}

func (x *DocItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocItem.ProtoReflect.Descriptor instead.
func (*DocItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *DocItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DocItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DocItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DocStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocItem             `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocStatusResponse) Reset() {
	*x = DocStatusResponse{}
	mi := &file_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocStatusResponse) ProtoMessage() {}

func (x *DocStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocStatusResponse.ProtoReflect.Descriptor instead.
func (*DocStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *DocStatusResponse) GetDocuments() []*DocItem {
	if x != nil {
		return x.Documents
	}
	return nil
}

type LaundryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Building      string                 `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaundryRequest) Reset() {
	*x = LaundryRequest{}
	mi := &file_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaundryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaundryRequest) ProtoMessage() {}

func (x *LaundryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaundryRequest.ProtoReflect.Descriptor instead.
func (*LaundryRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *LaundryRequest) GetBuilding() string {
	if x != nil {
		return x.Building
	}
	return ""
}

type LaundryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     int32                  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextFree      string                 `protobuf:"bytes,3,opt,name=next_free,json=nextFree,proto3" json:"next_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaundryResponse) Reset() {
	*x = LaundryResponse{}
	mi := &file_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaundryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaundryResponse) ProtoMessage() {}

func (x *LaundryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaundryResponse.ProtoReflect.Descriptor instead.
func (*LaundryResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{25}
}

func (x *LaundryResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *LaundryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LaundryResponse) GetNextFree() string {
	if x != nil {
		return x.NextFree
	}
	return ""
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x05proto\")\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x02R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"[\n" +
	"\x0ePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\"R\n" +
	"\x0fPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"N\n" +
	"\x12CertificateRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x19\n" +
	"\bdoc_type\x18\x02 \x01(\tR\adocType\"L\n" +
	"\x13CertificateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"a\n" +
	"\x14ProfileUpdateRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"1\n" +
	"\x15ProfileUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15FinanceHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"k\n" +
	"\x0fTransactionItem\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"T\n" +
	"\x16FinanceHistoryResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.proto.TransactionItemR\ftransactions\"1\n" +
	"\x10DormitoryRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"Y\n" +
	"\x11DormitoryResponse\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\bbuilding\x18\x02 \x01(\tR\bbuilding\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\tR\x05floor\"P\n" +
	"\rRepairRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"E\n" +
	"\x0eRepairResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"3\n" +
	"\x12ScholarshipRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\x80\x01\n" +
	"\x13ScholarshipResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12!\n" +
	"\fnext_payment\x18\x04 \x01(\tR\vnextPayment\"4\n" +
	"\x13LibraryDebtsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"@\n" +
	"\x14LibraryDebtsResponse\x12\x14\n" +
	"\x05books\x18\x01 \x03(\tR\x05books\x12\x12\n" +
	"\x04fine\x18\x02 \x01(\x02R\x04fine\"b\n" +
	"\x12ReserveBookRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"J\n" +
	"\x13ReserveBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bdue_date\x18\x02 \x01(\tR\adueDate\"1\n" +
	"\x10DocStatusRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"d\n" +
	"\aDocItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"A\n" +
	"\x11DocStatusResponse\x12,\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0e.proto.DocItemR\tdocuments\",\n" +
	"\x0eLaundryRequest\x12\x1a\n" +
	"\bbuilding\x18\x01 \x01(\tR\bbuilding\"b\n" +
	"\x0fLaundryResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x05R\tavailable\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1b\n" +
	"\tnext_free\x18\x03 \x01(\tR\bnextFree2\x80\a\n" +
	"\fAdminService\x12B\n" +
	"\x11GetAccountBalance\x12\x15.proto.BalanceRequest\x1a\x16.proto.BalanceResponse\x12@\n" +
	"\x0fInitiatePayment\x12\x15.proto.PaymentRequest\x1a\x16.proto.PaymentResponse\x12K\n" +
	"\x12RequestCertificate\x12\x19.proto.CertificateRequest\x1a\x1a.proto.CertificateResponse\x12Q\n" +
	"\x14UpdateStudentProfile\x12\x1b.proto.ProfileUpdateRequest\x1a\x1c.proto.ProfileUpdateResponse\x12P\n" +
	"\x11GetFinanceHistory\x12\x1c.proto.FinanceHistoryRequest\x1a\x1d.proto.FinanceHistoryResponse\x12E\n" +
	"\x10GetDormitoryInfo\x12\x17.proto.DormitoryRequest\x1a\x18.proto.DormitoryResponse\x12@\n" +
	"\x11RequestDormRepair\x12\x14.proto.RepairRequest\x1a\x15.proto.RepairResponse\x12K\n" +
	"\x12GetScholarshipInfo\x12\x19.proto.ScholarshipRequest\x1a\x1a.proto.ScholarshipResponse\x12J\n" +
	"\x0fGetLibraryDebts\x12\x1a.proto.LibraryDebtsRequest\x1a\x1b.proto.LibraryDebtsResponse\x12K\n" +
	"\x12ReserveLibraryBook\x12\x19.proto.ReserveBookRequest\x1a\x1a.proto.ReserveBookResponse\x12F\n" +
	"\x11GetDocumentStatus\x12\x17.proto.DocStatusRequest\x1a\x18.proto.DocStatusResponse\x12A\n" +
	"\x10GetLaundryStatus\x12\x15.proto.LaundryRequest\x1a\x16.proto.LaundryResponseB\x15Z\x13aitu-superapp/protob\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_admin_proto_goTypes = []any{
	(*BalanceRequest)(nil),         // 0: proto.BalanceRequest
	(*BalanceResponse)(nil),        // 1: proto.BalanceResponse
	(*PaymentRequest)(nil),         // 2: proto.PaymentRequest
	(*PaymentResponse)(nil),        // 3: proto.PaymentResponse
	(*CertificateRequest)(nil),     // 4: proto.CertificateRequest
	(*CertificateResponse)(nil),    // 5: proto.CertificateResponse
	(*ProfileUpdateRequest)(nil),   // 6: proto.ProfileUpdateRequest
	(*ProfileUpdateResponse)(nil),  // 7: proto.ProfileUpdateResponse
	(*FinanceHistoryRequest)(nil),  // 8: proto.FinanceHistoryRequest
	(*TransactionItem)(nil),        // 9: proto.TransactionItem
	(*FinanceHistoryResponse)(nil), // 10: proto.FinanceHistoryResponse
	(*DormitoryRequest)(nil),       // 11: proto.DormitoryRequest
	(*DormitoryResponse)(nil),      // 12: proto.DormitoryResponse
	(*RepairRequest)(nil),          // 13: proto.RepairRequest
	(*RepairResponse)(nil),         // 14: proto.RepairResponse
	(*ScholarshipRequest)(nil),     // 15: proto.ScholarshipRequest
	(*ScholarshipResponse)(nil),    // 16: proto.ScholarshipResponse
	(*LibraryDebtsRequest)(nil),    // 17: proto.LibraryDebtsRequest
	(*LibraryDebtsResponse)(nil),   // 18: proto.LibraryDebtsResponse
	(*ReserveBookRequest)(nil),     // 19: proto.ReserveBookRequest
	(*ReserveBookResponse)(nil),    // 20: proto.ReserveBookResponse
	(*DocStatusRequest)(nil),       // 21: proto.DocStatusRequest
	(*DocItem)(nil),                // 22: proto.DocItem
	(*DocStatusResponse)(nil),      // 23: proto.DocStatusResponse
	(*LaundryRequest)(nil),         // 24: proto.LaundryRequest
	(*LaundryResponse)(nil),        // 25: proto.LaundryResponse
}
var file_proto_admin_proto_depIdxs = []int32{
	9,  // 0: proto.FinanceHistoryResponse.transactions:type_name -> proto.TransactionItem
	22, // 1: proto.DocStatusResponse.documents:type_name -> proto.DocItem
	0,  // 2: proto.AdminService.GetAccountBalance:input_type -> proto.BalanceRequest
	2,  // 3: proto.AdminService.InitiatePayment:input_type -> proto.PaymentRequest
	4,  // 4: proto.AdminService.RequestCertificate:input_type -> proto.CertificateRequest
	6,  // 5: proto.AdminService.UpdateStudentProfile:input_type -> proto.ProfileUpdateRequest
	8,  // 6: proto.AdminService.GetFinanceHistory:input_type -> proto.FinanceHistoryRequest
	11, // 7: proto.AdminService.GetDormitoryInfo:input_type -> proto.DormitoryRequest
	13, // 8: proto.AdminService.RequestDormRepair:input_type -> proto.RepairRequest
	15, // 9: proto.AdminService.GetScholarshipInfo:input_type -> proto.ScholarshipRequest
	17, // 10: proto.AdminService.GetLibraryDebts:input_type -> proto.LibraryDebtsRequest
	19, // 11: proto.AdminService.ReserveLibraryBook:input_type -> proto.ReserveBookRequest
	21, // 12: proto.AdminService.GetDocumentStatus:input_type -> proto.DocStatusRequest
	24, // 13: proto.AdminService.GetLaundryStatus:input_type -> proto.LaundryRequest
	1,  // 14: proto.AdminService.GetAccountBalance:output_type -> proto.BalanceResponse
	3,  // 15: proto.AdminService.InitiatePayment:output_type -> proto.PaymentResponse
	5,  // 16: proto.AdminService.RequestCertificate:output_type -> proto.CertificateResponse
	7,  // 17: proto.AdminService.UpdateStudentProfile:output_type -> proto.ProfileUpdateResponse
	10, // 18: proto.AdminService.GetFinanceHistory:output_type -> proto.FinanceHistoryResponse
	12, // 19: proto.AdminService.GetDormitoryInfo:output_type -> proto.DormitoryResponse
	14, // 20: proto.AdminService.RequestDormRepair:output_type -> proto.RepairResponse
	16, // 21: proto.AdminService.GetScholarshipInfo:output_type -> proto.ScholarshipResponse
	18, // 22: proto.AdminService.GetLibraryDebts:output_type -> proto.LibraryDebtsResponse
	20, // 23: proto.AdminService.ReserveLibraryBook:output_type -> proto.ReserveBookResponse
	23, // 24: proto.AdminService.GetDocumentStatus:output_type -> proto.DocStatusResponse
	25, // 25: proto.AdminService.GetLaundryStatus:output_type -> proto.LaundryResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
