// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/community.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunityService_BookCoworkingSpace_FullMethodName      = "/proto.CommunityService/BookCoworkingSpace"
	CommunityService_RegisterForEvent_FullMethodName        = "/proto.CommunityService/RegisterForEvent"
	CommunityService_CreateMarketplaceAd_FullMethodName     = "/proto.CommunityService/CreateMarketplaceAd"
	CommunityService_SubmitFeedback_FullMethodName          = "/proto.CommunityService/SubmitFeedback"
	CommunityService_GetEventsList_FullMethodName           = "/proto.CommunityService/GetEventsList"
	CommunityService_CancelBooking_FullMethodName           = "/proto.CommunityService/CancelBooking"
	CommunityService_GetCoworkingSpaces_FullMethodName      = "/proto.CommunityService/GetCoworkingSpaces"
	CommunityService_GetMarketplaceItems_FullMethodName     = "/proto.CommunityService/GetMarketplaceItems"
	CommunityService_ReportLostFound_FullMethodName         = "/proto.CommunityService/ReportLostFound"
	CommunityService_GetLostFoundList_FullMethodName        = "/proto.CommunityService/GetLostFoundList"
	CommunityService_GetNewsFeed_FullMethodName             = "/proto.CommunityService/GetNewsFeed"
	CommunityService_CancelEventRegistration_FullMethodName = "/proto.CommunityService/CancelEventRegistration"
)

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunityServiceClient interface {
	BookCoworkingSpace(ctx context.Context, in *BookSpaceRequest, opts ...grpc.CallOption) (*BookSpaceResponse, error)
	RegisterForEvent(ctx context.Context, in *EventRegistrationRequest, opts ...grpc.CallOption) (*EventRegistrationResponse, error)
	CreateMarketplaceAd(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error)
	SubmitFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	GetEventsList(ctx context.Context, in *EventsListRequest, opts ...grpc.CallOption) (*EventsListResponse, error)
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error)
	GetCoworkingSpaces(ctx context.Context, in *CoworkingSpacesRequest, opts ...grpc.CallOption) (*CoworkingSpacesResponse, error)
	GetMarketplaceItems(ctx context.Context, in *MarketplaceRequest, opts ...grpc.CallOption) (*MarketplaceResponse, error)
	ReportLostFound(ctx context.Context, in *LostFoundRequest, opts ...grpc.CallOption) (*LostFoundResponse, error)
	GetLostFoundList(ctx context.Context, in *GetLostFoundRequest, opts ...grpc.CallOption) (*GetLostFoundResponse, error)
	GetNewsFeed(ctx context.Context, in *NewsFeedRequest, opts ...grpc.CallOption) (*NewsFeedResponse, error)
	CancelEventRegistration(ctx context.Context, in *CancelEventRequest, opts ...grpc.CallOption) (*CancelEventResponse, error)
}

type communityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunityServiceClient(cc grpc.ClientConnInterface) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) BookCoworkingSpace(ctx context.Context, in *BookSpaceRequest, opts ...grpc.CallOption) (*BookSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookSpaceResponse)
	err := c.cc.Invoke(ctx, CommunityService_BookCoworkingSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) RegisterForEvent(ctx context.Context, in *EventRegistrationRequest, opts ...grpc.CallOption) (*EventRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventRegistrationResponse)
	err := c.cc.Invoke(ctx, CommunityService_RegisterForEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) CreateMarketplaceAd(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*AdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdResponse)
	err := c.cc.Invoke(ctx, CommunityService_CreateMarketplaceAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) SubmitFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, CommunityService_SubmitFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetEventsList(ctx context.Context, in *EventsListRequest, opts ...grpc.CallOption) (*EventsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsListResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetEventsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBookingResponse)
	err := c.cc.Invoke(ctx, CommunityService_CancelBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetCoworkingSpaces(ctx context.Context, in *CoworkingSpacesRequest, opts ...grpc.CallOption) (*CoworkingSpacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoworkingSpacesResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetCoworkingSpaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetMarketplaceItems(ctx context.Context, in *MarketplaceRequest, opts ...grpc.CallOption) (*MarketplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketplaceResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetMarketplaceItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) ReportLostFound(ctx context.Context, in *LostFoundRequest, opts ...grpc.CallOption) (*LostFoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LostFoundResponse)
	err := c.cc.Invoke(ctx, CommunityService_ReportLostFound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetLostFoundList(ctx context.Context, in *GetLostFoundRequest, opts ...grpc.CallOption) (*GetLostFoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLostFoundResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetLostFoundList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetNewsFeed(ctx context.Context, in *NewsFeedRequest, opts ...grpc.CallOption) (*NewsFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsFeedResponse)
	err := c.cc.Invoke(ctx, CommunityService_GetNewsFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) CancelEventRegistration(ctx context.Context, in *CancelEventRequest, opts ...grpc.CallOption) (*CancelEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelEventResponse)
	err := c.cc.Invoke(ctx, CommunityService_CancelEventRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
// All implementations must embed UnimplementedCommunityServiceServer
// for forward compatibility.
type CommunityServiceServer interface {
	BookCoworkingSpace(context.Context, *BookSpaceRequest) (*BookSpaceResponse, error)
	RegisterForEvent(context.Context, *EventRegistrationRequest) (*EventRegistrationResponse, error)
	CreateMarketplaceAd(context.Context, *AdRequest) (*AdResponse, error)
	SubmitFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
	GetEventsList(context.Context, *EventsListRequest) (*EventsListResponse, error)
	CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error)
	GetCoworkingSpaces(context.Context, *CoworkingSpacesRequest) (*CoworkingSpacesResponse, error)
	GetMarketplaceItems(context.Context, *MarketplaceRequest) (*MarketplaceResponse, error)
	ReportLostFound(context.Context, *LostFoundRequest) (*LostFoundResponse, error)
	GetLostFoundList(context.Context, *GetLostFoundRequest) (*GetLostFoundResponse, error)
	GetNewsFeed(context.Context, *NewsFeedRequest) (*NewsFeedResponse, error)
	CancelEventRegistration(context.Context, *CancelEventRequest) (*CancelEventResponse, error)
	mustEmbedUnimplementedCommunityServiceServer()
}

// UnimplementedCommunityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunityServiceServer struct{}

func (UnimplementedCommunityServiceServer) BookCoworkingSpace(context.Context, *BookSpaceRequest) (*BookSpaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BookCoworkingSpace not implemented")
}
func (UnimplementedCommunityServiceServer) RegisterForEvent(context.Context, *EventRegistrationRequest) (*EventRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterForEvent not implemented")
}
func (UnimplementedCommunityServiceServer) CreateMarketplaceAd(context.Context, *AdRequest) (*AdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMarketplaceAd not implemented")
}
func (UnimplementedCommunityServiceServer) SubmitFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFeedback not implemented")
}
func (UnimplementedCommunityServiceServer) GetEventsList(context.Context, *EventsListRequest) (*EventsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsList not implemented")
}
func (UnimplementedCommunityServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedCommunityServiceServer) GetCoworkingSpaces(context.Context, *CoworkingSpacesRequest) (*CoworkingSpacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoworkingSpaces not implemented")
}
func (UnimplementedCommunityServiceServer) GetMarketplaceItems(context.Context, *MarketplaceRequest) (*MarketplaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketplaceItems not implemented")
}
func (UnimplementedCommunityServiceServer) ReportLostFound(context.Context, *LostFoundRequest) (*LostFoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLostFound not implemented")
}
func (UnimplementedCommunityServiceServer) GetLostFoundList(context.Context, *GetLostFoundRequest) (*GetLostFoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLostFoundList not implemented")
}
func (UnimplementedCommunityServiceServer) GetNewsFeed(context.Context, *NewsFeedRequest) (*NewsFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewsFeed not implemented")
}
func (UnimplementedCommunityServiceServer) CancelEventRegistration(context.Context, *CancelEventRequest) (*CancelEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelEventRegistration not implemented")
}
func (UnimplementedCommunityServiceServer) mustEmbedUnimplementedCommunityServiceServer() {}
func (UnimplementedCommunityServiceServer) testEmbeddedByValue()                          {}

// UnsafeCommunityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunityServiceServer will
// result in compilation errors.
type UnsafeCommunityServiceServer interface {
	mustEmbedUnimplementedCommunityServiceServer()
}

func RegisterCommunityServiceServer(s grpc.ServiceRegistrar, srv CommunityServiceServer) {
	// If the following call panics, it indicates UnimplementedCommunityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunityService_ServiceDesc, srv)
}

func _CommunityService_BookCoworkingSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).BookCoworkingSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_BookCoworkingSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).BookCoworkingSpace(ctx, req.(*BookSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_RegisterForEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).RegisterForEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_RegisterForEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).RegisterForEvent(ctx, req.(*EventRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_CreateMarketplaceAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).CreateMarketplaceAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_CreateMarketplaceAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).CreateMarketplaceAd(ctx, req.(*AdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_SubmitFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).SubmitFeedback(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetEventsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetEventsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetEventsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetEventsList(ctx, req.(*EventsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetCoworkingSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoworkingSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetCoworkingSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetCoworkingSpaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetCoworkingSpaces(ctx, req.(*CoworkingSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetMarketplaceItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetMarketplaceItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetMarketplaceItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetMarketplaceItems(ctx, req.(*MarketplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_ReportLostFound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LostFoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).ReportLostFound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_ReportLostFound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).ReportLostFound(ctx, req.(*LostFoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetLostFoundList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLostFoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetLostFoundList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetLostFoundList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetLostFoundList(ctx, req.(*GetLostFoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetNewsFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetNewsFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetNewsFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetNewsFeed(ctx, req.(*NewsFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_CancelEventRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).CancelEventRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_CancelEventRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).CancelEventRegistration(ctx, req.(*CancelEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunityService_ServiceDesc is the grpc.ServiceDesc for CommunityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookCoworkingSpace",
			Handler:    _CommunityService_BookCoworkingSpace_Handler,
		},
		{
			MethodName: "RegisterForEvent",
			Handler:    _CommunityService_RegisterForEvent_Handler,
		},
		{
			MethodName: "CreateMarketplaceAd",
			Handler:    _CommunityService_CreateMarketplaceAd_Handler,
		},
		{
			MethodName: "SubmitFeedback",
			Handler:    _CommunityService_SubmitFeedback_Handler,
		},
		{
			MethodName: "GetEventsList",
			Handler:    _CommunityService_GetEventsList_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _CommunityService_CancelBooking_Handler,
		},
		{
			MethodName: "GetCoworkingSpaces",
			Handler:    _CommunityService_GetCoworkingSpaces_Handler,
		},
		{
			MethodName: "GetMarketplaceItems",
			Handler:    _CommunityService_GetMarketplaceItems_Handler,
		},
		{
			MethodName: "ReportLostFound",
			Handler:    _CommunityService_ReportLostFound_Handler,
		},
		{
			MethodName: "GetLostFoundList",
			Handler:    _CommunityService_GetLostFoundList_Handler,
		},
		{
			MethodName: "GetNewsFeed",
			Handler:    _CommunityService_GetNewsFeed_Handler,
		},
		{
			MethodName: "CancelEventRegistration",
			Handler:    _CommunityService_CancelEventRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/community.proto",
}
