// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/community.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSpaceRequest) Reset() {
	*x = BookSpaceRequest{}
	mi := &file_proto_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSpaceRequest) ProtoMessage() {}

func (x *BookSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSpaceRequest.ProtoReflect.Descriptor instead.
func (*BookSpaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{0}
}

func (x *BookSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *BookSpaceRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *BookSpaceRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BookSpaceRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type BookSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSpaceResponse) Reset() {
	*x = BookSpaceResponse{}
	mi := &file_proto_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSpaceResponse) ProtoMessage() {}

func (x *BookSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSpaceResponse.ProtoReflect.Descriptor instead.
func (*BookSpaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{1}
}

func (x *BookSpaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BookSpaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BookSpaceResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type EventRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRegistrationRequest) Reset() {
	*x = EventRegistrationRequest{}
	mi := &file_proto_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRegistrationRequest) ProtoMessage() {}

func (x *EventRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRegistrationRequest.ProtoReflect.Descriptor instead.
func (*EventRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{2}
}

func (x *EventRegistrationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventRegistrationRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type EventRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRegistrationResponse) Reset() {
	*x = EventRegistrationResponse{}
	mi := &file_proto_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRegistrationResponse) ProtoMessage() {}

func (x *EventRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRegistrationResponse.ProtoReflect.Descriptor instead.
func (*EventRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{3}
}

func (x *EventRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdRequest) Reset() {
	*x = AdRequest{}
	mi := &file_proto_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdRequest) ProtoMessage() {}

func (x *AdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdRequest.ProtoReflect.Descriptor instead.
func (*AdRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{4}
}

func (x *AdRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AdId          string                 `protobuf:"bytes,2,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdResponse) Reset() {
	*x = AdResponse{}
	mi := &file_proto_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdResponse) ProtoMessage() {}

func (x *AdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdResponse.ProtoReflect.Descriptor instead.
func (*AdResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{5}
}

func (x *AdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdResponse) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type FeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackRequest) Reset() {
	*x = FeedbackRequest{}
	mi := &file_proto_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRequest) ProtoMessage() {}

func (x *FeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRequest.ProtoReflect.Descriptor instead.
func (*FeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{6}
}

func (x *FeedbackRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *FeedbackRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FeedbackRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_proto_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{7}
}

func (x *FeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FeedbackResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type EventsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsListRequest) Reset() {
	*x = EventsListRequest{}
	mi := &file_proto_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListRequest) ProtoMessage() {}

func (x *EventsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsListRequest.ProtoReflect.Descriptor instead.
func (*EventsListRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{8}
}

type EventItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	SpotsLeft     int32                  `protobuf:"varint,5,opt,name=spots_left,json=spotsLeft,proto3" json:"spots_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventItem) Reset() {
	*x = EventItem{}
	mi := &file_proto_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventItem) ProtoMessage() {}

func (x *EventItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventItem.ProtoReflect.Descriptor instead.
func (*EventItem) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{9}
}

func (x *EventItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EventItem) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventItem) GetSpotsLeft() int32 {
	if x != nil {
		return x.SpotsLeft
	}
	return 0
}

type EventsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventItem           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsListResponse) Reset() {
	*x = EventsListResponse{}
	mi := &file_proto_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListResponse) ProtoMessage() {}

func (x *EventsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsListResponse.ProtoReflect.Descriptor instead.
func (*EventsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{10}
}

func (x *EventsListResponse) GetEvents() []*EventItem {
	if x != nil {
		return x.Events
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{11}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{12}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CoworkingSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoworkingSpacesRequest) Reset() {
	*x = CoworkingSpacesRequest{}
	mi := &file_proto_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoworkingSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoworkingSpacesRequest) ProtoMessage() {}

func (x *CoworkingSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoworkingSpacesRequest.ProtoReflect.Descriptor instead.
func (*CoworkingSpacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{13}
}

type SpaceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceItem) Reset() {
	*x = SpaceItem{}
	mi := &file_proto_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceItem) ProtoMessage() {}

func (x *SpaceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceItem.ProtoReflect.Descriptor instead.
func (*SpaceItem) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{14}
}

func (x *SpaceItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SpaceItem) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CoworkingSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*SpaceItem           `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoworkingSpacesResponse) Reset() {
	*x = CoworkingSpacesResponse{}
	mi := &file_proto_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoworkingSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoworkingSpacesResponse) ProtoMessage() {}

func (x *CoworkingSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoworkingSpacesResponse.ProtoReflect.Descriptor instead.
func (*CoworkingSpacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{15}
}

func (x *CoworkingSpacesResponse) GetSpaces() []*SpaceItem {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type MarketplaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceRequest) Reset() {
	*x = MarketplaceRequest{}
	mi := &file_proto_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceRequest) ProtoMessage() {}

func (x *MarketplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceRequest.ProtoReflect.Descriptor instead.
func (*MarketplaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{16}
}

type MarketplaceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Seller        string                 `protobuf:"bytes,4,opt,name=seller,proto3" json:"seller,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceItem) Reset() {
	*x = MarketplaceItem{}
	mi := &file_proto_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceItem) ProtoMessage() {}

func (x *MarketplaceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceItem.ProtoReflect.Descriptor instead.
func (*MarketplaceItem) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{17}
}

func (x *MarketplaceItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarketplaceItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MarketplaceItem) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketplaceItem) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *MarketplaceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MarketplaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MarketplaceItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceResponse) Reset() {
	*x = MarketplaceResponse{}
	mi := &file_proto_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceResponse) ProtoMessage() {}

func (x *MarketplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceResponse.ProtoReflect.Descriptor instead.
func (*MarketplaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{18}
}

func (x *MarketplaceResponse) GetItems() []*MarketplaceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LostFoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LostFoundRequest) Reset() {
	*x = LostFoundRequest{}
	mi := &file_proto_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostFoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostFoundRequest) ProtoMessage() {}

func (x *LostFoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostFoundRequest.ProtoReflect.Descriptor instead.
func (*LostFoundRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{19}
}

func (x *LostFoundRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LostFoundRequest) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *LostFoundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LostFoundRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LostFoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LostFoundResponse) Reset() {
	*x = LostFoundResponse{}
	mi := &file_proto_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostFoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostFoundResponse) ProtoMessage() {}

func (x *LostFoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostFoundResponse.ProtoReflect.Descriptor instead.
func (*LostFoundResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{20}
}

func (x *LostFoundResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LostFoundResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLostFoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLostFoundRequest) Reset() {
	*x = GetLostFoundRequest{}
	mi := &file_proto_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLostFoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLostFoundRequest) ProtoMessage() {}

func (x *GetLostFoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLostFoundRequest.ProtoReflect.Descriptor instead.
func (*GetLostFoundRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{21}
}

type LostFoundItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LostFoundItem) Reset() {
	*x = LostFoundItem{}
	mi := &file_proto_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostFoundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostFoundItem) ProtoMessage() {}

func (x *LostFoundItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostFoundItem.ProtoReflect.Descriptor instead.
func (*LostFoundItem) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{22}
}

func (x *LostFoundItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LostFoundItem) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *LostFoundItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LostFoundItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LostFoundItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetLostFoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LostFoundItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLostFoundResponse) Reset() {
	*x = GetLostFoundResponse{}
	mi := &file_proto_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLostFoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLostFoundResponse) ProtoMessage() {}

func (x *GetLostFoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLostFoundResponse.ProtoReflect.Descriptor instead.
func (*GetLostFoundResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{23}
}

func (x *GetLostFoundResponse) GetItems() []*LostFoundItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type NewsFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsFeedRequest) Reset() {
	*x = NewsFeedRequest{}
	mi := &file_proto_community_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsFeedRequest) ProtoMessage() {}

func (x *NewsFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsFeedRequest.ProtoReflect.Descriptor instead.
func (*NewsFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{24}
}

type NewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_proto_community_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{25}
}

func (x *NewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NewsItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NewsItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NewsFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*NewsItem            `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsFeedResponse) Reset() {
	*x = NewsFeedResponse{}
	mi := &file_proto_community_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsFeedResponse) ProtoMessage() {}

func (x *NewsFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsFeedResponse.ProtoReflect.Descriptor instead.
func (*NewsFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{26}
}

func (x *NewsFeedResponse) GetNews() []*NewsItem {
	if x != nil {
		return x.News
	}
	return nil
}

type CancelEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventRequest) Reset() {
	*x = CancelEventRequest{}
	mi := &file_proto_community_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventRequest) ProtoMessage() {}

func (x *CancelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventRequest.ProtoReflect.Descriptor instead.
func (*CancelEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{27}
}

func (x *CancelEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CancelEventRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type CancelEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventResponse) Reset() {
	*x = CancelEventResponse{}
	mi := &file_proto_community_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventResponse) ProtoMessage() {}

func (x *CancelEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_community_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventResponse.ProtoReflect.Descriptor instead.
func (*CancelEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_community_proto_rawDescGZIP(), []int{28}
}

func (x *CancelEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_community_proto protoreflect.FileDescriptor

const file_proto_community_proto_rawDesc = "" +
	"\n" +
	"\x15proto/community.proto\x12\x05proto\"\x86\x01\n" +
	"\x10BookSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"f\n" +
	"\x11BookSpaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"T\n" +
	"\x18EventRegistrationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"O\n" +
	"\x19EventRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\tAdRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\";\n" +
	"\n" +
	"AdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05ad_id\x18\x02 \x01(\tR\x04adId\"`\n" +
	"\x0fFeedbackRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"I\n" +
	"\x10FeedbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\"\x13\n" +
	"\x11EventsListRequest\"\x80\x01\n" +
	"\tEventItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"spots_left\x18\x05 \x01(\x05R\tspotsLeft\">\n" +
	"\x12EventsListResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.proto.EventItemR\x06events\"T\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"1\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16CoworkingSpacesRequest\"i\n" +
	"\tSpaceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"C\n" +
	"\x17CoworkingSpacesResponse\x12(\n" +
	"\x06spaces\x18\x01 \x03(\v2\x10.proto.SpaceItemR\x06spaces\"\x14\n" +
	"\x12MarketplaceRequest\"\x87\x01\n" +
	"\x0fMarketplaceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x16\n" +
	"\x06seller\x18\x04 \x01(\tR\x06seller\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"C\n" +
	"\x13MarketplaceResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.proto.MarketplaceItemR\x05items\"\x7f\n" +
	"\x10LostFoundRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"=\n" +
	"\x11LostFoundResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x15\n" +
	"\x13GetLostFoundRequest\"\x81\x01\n" +
	"\rLostFoundItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"B\n" +
	"\x14GetLostFoundResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.proto.LostFoundItemR\x05items\"\x11\n" +
	"\x0fNewsFeedRequest\"z\n" +
	"\bNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"7\n" +
	"\x10NewsFeedResponse\x12#\n" +
	"\x04news\x18\x01 \x03(\v2\x0f.proto.NewsItemR\x04news\"N\n" +
	"\x12CancelEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"/\n" +
	"\x13CancelEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8b\a\n" +
	"\x10CommunityService\x12G\n" +
	"\x12BookCoworkingSpace\x12\x17.proto.BookSpaceRequest\x1a\x18.proto.BookSpaceResponse\x12U\n" +
	"\x10RegisterForEvent\x12\x1f.proto.EventRegistrationRequest\x1a .proto.EventRegistrationResponse\x12:\n" +
	"\x13CreateMarketplaceAd\x12\x10.proto.AdRequest\x1a\x11.proto.AdResponse\x12A\n" +
	"\x0eSubmitFeedback\x12\x16.proto.FeedbackRequest\x1a\x17.proto.FeedbackResponse\x12D\n" +
	"\rGetEventsList\x12\x18.proto.EventsListRequest\x1a\x19.proto.EventsListResponse\x12J\n" +
	"\rCancelBooking\x12\x1b.proto.CancelBookingRequest\x1a\x1c.proto.CancelBookingResponse\x12S\n" +
	"\x12GetCoworkingSpaces\x12\x1d.proto.CoworkingSpacesRequest\x1a\x1e.proto.CoworkingSpacesResponse\x12L\n" +
	"\x13GetMarketplaceItems\x12\x19.proto.MarketplaceRequest\x1a\x1a.proto.MarketplaceResponse\x12D\n" +
	"\x0fReportLostFound\x12\x17.proto.LostFoundRequest\x1a\x18.proto.LostFoundResponse\x12K\n" +
	"\x10GetLostFoundList\x12\x1a.proto.GetLostFoundRequest\x1a\x1b.proto.GetLostFoundResponse\x12>\n" +
	"\vGetNewsFeed\x12\x16.proto.NewsFeedRequest\x1a\x17.proto.NewsFeedResponse\x12P\n" +
	"\x17CancelEventRegistration\x12\x19.proto.CancelEventRequest\x1a\x1a.proto.CancelEventResponseB\x15Z\x13aitu-superapp/protob\x06proto3"

var (
	file_proto_community_proto_rawDescOnce sync.Once
	file_proto_community_proto_rawDescData []byte
)

func file_proto_community_proto_rawDescGZIP() []byte {
	file_proto_community_proto_rawDescOnce.Do(func() {
		file_proto_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_community_proto_rawDesc), len(file_proto_community_proto_rawDesc)))
	})
	return file_proto_community_proto_rawDescData
}

var file_proto_community_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_community_proto_goTypes = []any{
	(*BookSpaceRequest)(nil),          // 0: proto.BookSpaceRequest
	(*BookSpaceResponse)(nil),         // 1: proto.BookSpaceResponse
	(*EventRegistrationRequest)(nil),  // 2: proto.EventRegistrationRequest
	(*EventRegistrationResponse)(nil), // 3: proto.EventRegistrationResponse
	(*AdRequest)(nil),                 // 4: proto.AdRequest
	(*AdResponse)(nil),                // 5: proto.AdResponse
	(*FeedbackRequest)(nil),           // 6: proto.FeedbackRequest
	(*FeedbackResponse)(nil),          // 7: proto.FeedbackResponse
	(*EventsListRequest)(nil),         // 8: proto.EventsListRequest
	(*EventItem)(nil),                 // 9: proto.EventItem
	(*EventsListResponse)(nil),        // 10: proto.EventsListResponse
	(*CancelBookingRequest)(nil),      // 11: proto.CancelBookingRequest
	(*CancelBookingResponse)(nil),     // 12: proto.CancelBookingResponse
	(*CoworkingSpacesRequest)(nil),    // 13: proto.CoworkingSpacesRequest
	(*SpaceItem)(nil),                 // 14: proto.SpaceItem
	(*CoworkingSpacesResponse)(nil),   // 15: proto.CoworkingSpacesResponse
	(*MarketplaceRequest)(nil),        // 16: proto.MarketplaceRequest
	(*MarketplaceItem)(nil),           // 17: proto.MarketplaceItem
	(*MarketplaceResponse)(nil),       // 18: proto.MarketplaceResponse
	(*LostFoundRequest)(nil),          // 19: proto.LostFoundRequest
	(*LostFoundResponse)(nil),         // 20: proto.LostFoundResponse
	(*GetLostFoundRequest)(nil),       // 21: proto.GetLostFoundRequest
	(*LostFoundItem)(nil),             // 22: proto.LostFoundItem
	(*GetLostFoundResponse)(nil),      // 23: proto.GetLostFoundResponse
	(*NewsFeedRequest)(nil),           // 24: proto.NewsFeedRequest
	(*NewsItem)(nil),                  // 25: proto.NewsItem
	(*NewsFeedResponse)(nil),          // 26: proto.NewsFeedResponse
	(*CancelEventRequest)(nil),        // 27: proto.CancelEventRequest
	(*CancelEventResponse)(nil),       // 28: proto.CancelEventResponse
}
var file_proto_community_proto_depIdxs = []int32{
	9,  // 0: proto.EventsListResponse.events:type_name -> proto.EventItem
	14, // 1: proto.CoworkingSpacesResponse.spaces:type_name -> proto.SpaceItem
	17, // 2: proto.MarketplaceResponse.items:type_name -> proto.MarketplaceItem
	22, // 3: proto.GetLostFoundResponse.items:type_name -> proto.LostFoundItem
	25, // 4: proto.NewsFeedResponse.news:type_name -> proto.NewsItem
	0,  // 5: proto.CommunityService.BookCoworkingSpace:input_type -> proto.BookSpaceRequest
	2,  // 6: proto.CommunityService.RegisterForEvent:input_type -> proto.EventRegistrationRequest
	4,  // 7: proto.CommunityService.CreateMarketplaceAd:input_type -> proto.AdRequest
	6,  // 8: proto.CommunityService.SubmitFeedback:input_type -> proto.FeedbackRequest
	8,  // 9: proto.CommunityService.GetEventsList:input_type -> proto.EventsListRequest
	11, // 10: proto.CommunityService.CancelBooking:input_type -> proto.CancelBookingRequest
	13, // 11: proto.CommunityService.GetCoworkingSpaces:input_type -> proto.CoworkingSpacesRequest
	16, // 12: proto.CommunityService.GetMarketplaceItems:input_type -> proto.MarketplaceRequest
	19, // 13: proto.CommunityService.ReportLostFound:input_type -> proto.LostFoundRequest
	21, // 14: proto.CommunityService.GetLostFoundList:input_type -> proto.GetLostFoundRequest
	24, // 15: proto.CommunityService.GetNewsFeed:input_type -> proto.NewsFeedRequest
	27, // 16: proto.CommunityService.CancelEventRegistration:input_type -> proto.CancelEventRequest
	1,  // 17: proto.CommunityService.BookCoworkingSpace:output_type -> proto.BookSpaceResponse
	3,  // 18: proto.CommunityService.RegisterForEvent:output_type -> proto.EventRegistrationResponse
	5,  // 19: proto.CommunityService.CreateMarketplaceAd:output_type -> proto.AdResponse
	7,  // 20: proto.CommunityService.SubmitFeedback:output_type -> proto.FeedbackResponse
	10, // 21: proto.CommunityService.GetEventsList:output_type -> proto.EventsListResponse
	12, // 22: proto.CommunityService.CancelBooking:output_type -> proto.CancelBookingResponse
	15, // 23: proto.CommunityService.GetCoworkingSpaces:output_type -> proto.CoworkingSpacesResponse
	18, // 24: proto.CommunityService.GetMarketplaceItems:output_type -> proto.MarketplaceResponse
	20, // 25: proto.CommunityService.ReportLostFound:output_type -> proto.LostFoundResponse
	23, // 26: proto.CommunityService.GetLostFoundList:output_type -> proto.GetLostFoundResponse
	26, // 27: proto.CommunityService.GetNewsFeed:output_type -> proto.NewsFeedResponse
	28, // 28: proto.CommunityService.CancelEventRegistration:output_type -> proto.CancelEventResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_community_proto_init() }
func file_proto_community_proto_init() {
	if File_proto_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_community_proto_rawDesc), len(file_proto_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_community_proto_goTypes,
		DependencyIndexes: file_proto_community_proto_depIdxs,
		MessageInfos:      file_proto_community_proto_msgTypes,
	}.Build()
	File_proto_community_proto = out.File
	file_proto_community_proto_goTypes = nil
	file_proto_community_proto_depIdxs = nil
}
