// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/education.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EducationService_GetStudentGPA_FullMethodName         = "/proto.EducationService/GetStudentGPA"
	EducationService_SubmitAttendance_FullMethodName      = "/proto.EducationService/SubmitAttendance"
	EducationService_EnrollToCourse_FullMethodName        = "/proto.EducationService/EnrollToCourse"
	EducationService_GetExamSchedule_FullMethodName       = "/proto.EducationService/GetExamSchedule"
	EducationService_DropCourse_FullMethodName            = "/proto.EducationService/DropCourse"
	EducationService_GetGrades_FullMethodName             = "/proto.EducationService/GetGrades"
	EducationService_GetScheduleToday_FullMethodName      = "/proto.EducationService/GetScheduleToday"
	EducationService_SearchTeacher_FullMethodName         = "/proto.EducationService/SearchTeacher"
	EducationService_GetCoursesCatalog_FullMethodName     = "/proto.EducationService/GetCoursesCatalog"
	EducationService_GetAttendanceStats_FullMethodName    = "/proto.EducationService/GetAttendanceStats"
	EducationService_GetTeacherOfficeHours_FullMethodName = "/proto.EducationService/GetTeacherOfficeHours"
	EducationService_GetStudentProfile_FullMethodName     = "/proto.EducationService/GetStudentProfile"
)

// EducationServiceClient is the client API for EducationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationServiceClient interface {
	GetStudentGPA(ctx context.Context, in *GPARequest, opts ...grpc.CallOption) (*GPAResponse, error)
	SubmitAttendance(ctx context.Context, in *AttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error)
	EnrollToCourse(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	GetExamSchedule(ctx context.Context, in *ExamScheduleRequest, opts ...grpc.CallOption) (*ExamScheduleResponse, error)
	DropCourse(ctx context.Context, in *DropCourseRequest, opts ...grpc.CallOption) (*DropCourseResponse, error)
	GetGrades(ctx context.Context, in *GetGradesRequest, opts ...grpc.CallOption) (*GetGradesResponse, error)
	GetScheduleToday(ctx context.Context, in *ScheduleTodayRequest, opts ...grpc.CallOption) (*ScheduleTodayResponse, error)
	SearchTeacher(ctx context.Context, in *SearchTeacherRequest, opts ...grpc.CallOption) (*SearchTeacherResponse, error)
	GetCoursesCatalog(ctx context.Context, in *CoursesRequest, opts ...grpc.CallOption) (*CoursesResponse, error)
	GetAttendanceStats(ctx context.Context, in *AttendanceStatsRequest, opts ...grpc.CallOption) (*AttendanceStatsResponse, error)
	GetTeacherOfficeHours(ctx context.Context, in *OfficeHoursRequest, opts ...grpc.CallOption) (*OfficeHoursResponse, error)
	GetStudentProfile(ctx context.Context, in *StudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error)
}

type educationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationServiceClient(cc grpc.ClientConnInterface) EducationServiceClient {
	return &educationServiceClient{cc}
}

func (c *educationServiceClient) GetStudentGPA(ctx context.Context, in *GPARequest, opts ...grpc.CallOption) (*GPAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPAResponse)
	err := c.cc.Invoke(ctx, EducationService_GetStudentGPA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) SubmitAttendance(ctx context.Context, in *AttendanceRequest, opts ...grpc.CallOption) (*AttendanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttendanceResponse)
	err := c.cc.Invoke(ctx, EducationService_SubmitAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) EnrollToCourse(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EducationService_EnrollToCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetExamSchedule(ctx context.Context, in *ExamScheduleRequest, opts ...grpc.CallOption) (*ExamScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamScheduleResponse)
	err := c.cc.Invoke(ctx, EducationService_GetExamSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) DropCourse(ctx context.Context, in *DropCourseRequest, opts ...grpc.CallOption) (*DropCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropCourseResponse)
	err := c.cc.Invoke(ctx, EducationService_DropCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetGrades(ctx context.Context, in *GetGradesRequest, opts ...grpc.CallOption) (*GetGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGradesResponse)
	err := c.cc.Invoke(ctx, EducationService_GetGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetScheduleToday(ctx context.Context, in *ScheduleTodayRequest, opts ...grpc.CallOption) (*ScheduleTodayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTodayResponse)
	err := c.cc.Invoke(ctx, EducationService_GetScheduleToday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) SearchTeacher(ctx context.Context, in *SearchTeacherRequest, opts ...grpc.CallOption) (*SearchTeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTeacherResponse)
	err := c.cc.Invoke(ctx, EducationService_SearchTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetCoursesCatalog(ctx context.Context, in *CoursesRequest, opts ...grpc.CallOption) (*CoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoursesResponse)
	err := c.cc.Invoke(ctx, EducationService_GetCoursesCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetAttendanceStats(ctx context.Context, in *AttendanceStatsRequest, opts ...grpc.CallOption) (*AttendanceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttendanceStatsResponse)
	err := c.cc.Invoke(ctx, EducationService_GetAttendanceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetTeacherOfficeHours(ctx context.Context, in *OfficeHoursRequest, opts ...grpc.CallOption) (*OfficeHoursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfficeHoursResponse)
	err := c.cc.Invoke(ctx, EducationService_GetTeacherOfficeHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetStudentProfile(ctx context.Context, in *StudentProfileRequest, opts ...grpc.CallOption) (*StudentProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentProfileResponse)
	err := c.cc.Invoke(ctx, EducationService_GetStudentProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationServiceServer is the server API for EducationService service.
// All implementations must embed UnimplementedEducationServiceServer
// for forward compatibility.
type EducationServiceServer interface {
	GetStudentGPA(context.Context, *GPARequest) (*GPAResponse, error)
	SubmitAttendance(context.Context, *AttendanceRequest) (*AttendanceResponse, error)
	EnrollToCourse(context.Context, *EnrollRequest) (*EnrollResponse, error)
	GetExamSchedule(context.Context, *ExamScheduleRequest) (*ExamScheduleResponse, error)
	DropCourse(context.Context, *DropCourseRequest) (*DropCourseResponse, error)
	GetGrades(context.Context, *GetGradesRequest) (*GetGradesResponse, error)
	GetScheduleToday(context.Context, *ScheduleTodayRequest) (*ScheduleTodayResponse, error)
	SearchTeacher(context.Context, *SearchTeacherRequest) (*SearchTeacherResponse, error)
	GetCoursesCatalog(context.Context, *CoursesRequest) (*CoursesResponse, error)
	GetAttendanceStats(context.Context, *AttendanceStatsRequest) (*AttendanceStatsResponse, error)
	GetTeacherOfficeHours(context.Context, *OfficeHoursRequest) (*OfficeHoursResponse, error)
	GetStudentProfile(context.Context, *StudentProfileRequest) (*StudentProfileResponse, error)
	mustEmbedUnimplementedEducationServiceServer()
}

// UnimplementedEducationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEducationServiceServer struct{}

func (UnimplementedEducationServiceServer) GetStudentGPA(context.Context, *GPARequest) (*GPAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentGPA not implemented")
}
func (UnimplementedEducationServiceServer) SubmitAttendance(context.Context, *AttendanceRequest) (*AttendanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAttendance not implemented")
}
func (UnimplementedEducationServiceServer) EnrollToCourse(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollToCourse not implemented")
}
func (UnimplementedEducationServiceServer) GetExamSchedule(context.Context, *ExamScheduleRequest) (*ExamScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExamSchedule not implemented")
}
func (UnimplementedEducationServiceServer) DropCourse(context.Context, *DropCourseRequest) (*DropCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCourse not implemented")
}
func (UnimplementedEducationServiceServer) GetGrades(context.Context, *GetGradesRequest) (*GetGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrades not implemented")
}
func (UnimplementedEducationServiceServer) GetScheduleToday(context.Context, *ScheduleTodayRequest) (*ScheduleTodayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScheduleToday not implemented")
}
func (UnimplementedEducationServiceServer) SearchTeacher(context.Context, *SearchTeacherRequest) (*SearchTeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTeacher not implemented")
}
func (UnimplementedEducationServiceServer) GetCoursesCatalog(context.Context, *CoursesRequest) (*CoursesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoursesCatalog not implemented")
}
func (UnimplementedEducationServiceServer) GetAttendanceStats(context.Context, *AttendanceStatsRequest) (*AttendanceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttendanceStats not implemented")
}
func (UnimplementedEducationServiceServer) GetTeacherOfficeHours(context.Context, *OfficeHoursRequest) (*OfficeHoursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherOfficeHours not implemented")
}
func (UnimplementedEducationServiceServer) GetStudentProfile(context.Context, *StudentProfileRequest) (*StudentProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentProfile not implemented")
}
func (UnimplementedEducationServiceServer) mustEmbedUnimplementedEducationServiceServer() {}
func (UnimplementedEducationServiceServer) testEmbeddedByValue()                          {}

// UnsafeEducationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationServiceServer will
// result in compilation errors.
type UnsafeEducationServiceServer interface {
	mustEmbedUnimplementedEducationServiceServer()
}

func RegisterEducationServiceServer(s grpc.ServiceRegistrar, srv EducationServiceServer) {
	// If the following call panics, it indicates UnimplementedEducationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EducationService_ServiceDesc, srv)
}

func _EducationService_GetStudentGPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetStudentGPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetStudentGPA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetStudentGPA(ctx, req.(*GPARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_SubmitAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).SubmitAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_SubmitAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).SubmitAttendance(ctx, req.(*AttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_EnrollToCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).EnrollToCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_EnrollToCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).EnrollToCourse(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetExamSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetExamSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetExamSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetExamSchedule(ctx, req.(*ExamScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_DropCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).DropCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_DropCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).DropCourse(ctx, req.(*DropCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetGrades(ctx, req.(*GetGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetScheduleToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTodayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetScheduleToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetScheduleToday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetScheduleToday(ctx, req.(*ScheduleTodayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_SearchTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).SearchTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_SearchTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).SearchTeacher(ctx, req.(*SearchTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetCoursesCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetCoursesCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetCoursesCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetCoursesCatalog(ctx, req.(*CoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetAttendanceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttendanceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetAttendanceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetAttendanceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetAttendanceStats(ctx, req.(*AttendanceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetTeacherOfficeHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfficeHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetTeacherOfficeHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetTeacherOfficeHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetTeacherOfficeHours(ctx, req.(*OfficeHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetStudentProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetStudentProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EducationService_GetStudentProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetStudentProfile(ctx, req.(*StudentProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationService_ServiceDesc is the grpc.ServiceDesc for EducationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EducationService",
	HandlerType: (*EducationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentGPA",
			Handler:    _EducationService_GetStudentGPA_Handler,
		},
		{
			MethodName: "SubmitAttendance",
			Handler:    _EducationService_SubmitAttendance_Handler,
		},
		{
			MethodName: "EnrollToCourse",
			Handler:    _EducationService_EnrollToCourse_Handler,
		},
		{
			MethodName: "GetExamSchedule",
			Handler:    _EducationService_GetExamSchedule_Handler,
		},
		{
			MethodName: "DropCourse",
			Handler:    _EducationService_DropCourse_Handler,
		},
		{
			MethodName: "GetGrades",
			Handler:    _EducationService_GetGrades_Handler,
		},
		{
			MethodName: "GetScheduleToday",
			Handler:    _EducationService_GetScheduleToday_Handler,
		},
		{
			MethodName: "SearchTeacher",
			Handler:    _EducationService_SearchTeacher_Handler,
		},
		{
			MethodName: "GetCoursesCatalog",
			Handler:    _EducationService_GetCoursesCatalog_Handler,
		},
		{
			MethodName: "GetAttendanceStats",
			Handler:    _EducationService_GetAttendanceStats_Handler,
		},
		{
			MethodName: "GetTeacherOfficeHours",
			Handler:    _EducationService_GetTeacherOfficeHours_Handler,
		},
		{
			MethodName: "GetStudentProfile",
			Handler:    _EducationService_GetStudentProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/education.proto",
}
