// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/education.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPARequest) Reset() {
	*x = GPARequest{}
	mi := &file_proto_education_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPARequest) ProtoMessage() {}

func (x *GPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPARequest.ProtoReflect.Descriptor instead.
func (*GPARequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{0}
}

func (x *GPARequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gpa           float32                `protobuf:"fixed32,1,opt,name=gpa,proto3" json:"gpa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPAResponse) Reset() {
	*x = GPAResponse{}
	mi := &file_proto_education_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPAResponse) ProtoMessage() {}

func (x *GPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPAResponse.ProtoReflect.Descriptor instead.
func (*GPAResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{1}
}

func (x *GPAResponse) GetGpa() float32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

type AttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceRequest) Reset() {
	*x = AttendanceRequest{}
	mi := &file_proto_education_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceRequest) ProtoMessage() {}

func (x *AttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceRequest.ProtoReflect.Descriptor instead.
func (*AttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{2}
}

func (x *AttendanceRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AttendanceRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *AttendanceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttendanceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type AttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceResponse) Reset() {
	*x = AttendanceResponse{}
	mi := &file_proto_education_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceResponse) ProtoMessage() {}

func (x *AttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceResponse.ProtoReflect.Descriptor instead.
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{3}
}

func (x *AttendanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_education_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnrollRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_education_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExamScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamScheduleRequest) Reset() {
	*x = ExamScheduleRequest{}
	mi := &file_proto_education_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamScheduleRequest) ProtoMessage() {}

func (x *ExamScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamScheduleRequest.ProtoReflect.Descriptor instead.
func (*ExamScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{6}
}

func (x *ExamScheduleRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ExamScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleJson  string                 `protobuf:"bytes,1,opt,name=schedule_json,json=scheduleJson,proto3" json:"schedule_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamScheduleResponse) Reset() {
	*x = ExamScheduleResponse{}
	mi := &file_proto_education_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamScheduleResponse) ProtoMessage() {}

func (x *ExamScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamScheduleResponse.ProtoReflect.Descriptor instead.
func (*ExamScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{7}
}

func (x *ExamScheduleResponse) GetScheduleJson() string {
	if x != nil {
		return x.ScheduleJson
	}
	return ""
}

type DropCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCourseRequest) Reset() {
	*x = DropCourseRequest{}
	mi := &file_proto_education_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCourseRequest) ProtoMessage() {}

func (x *DropCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCourseRequest.ProtoReflect.Descriptor instead.
func (*DropCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{8}
}

func (x *DropCourseRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DropCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DropCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCourseResponse) Reset() {
	*x = DropCourseResponse{}
	mi := &file_proto_education_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCourseResponse) ProtoMessage() {}

func (x *DropCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCourseResponse.ProtoReflect.Descriptor instead.
func (*DropCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{9}
}

func (x *DropCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DropCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradesRequest) Reset() {
	*x = GetGradesRequest{}
	mi := &file_proto_education_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradesRequest) ProtoMessage() {}

func (x *GetGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradesRequest.ProtoReflect.Descriptor instead.
func (*GetGradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{10}
}

func (x *GetGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeItem) Reset() {
	*x = GradeItem{}
	mi := &file_proto_education_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeItem) ProtoMessage() {}

func (x *GradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeItem.ProtoReflect.Descriptor instead.
func (*GradeItem) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{11}
}

func (x *GradeItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GradeItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*GradeItem           `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradesResponse) Reset() {
	*x = GetGradesResponse{}
	mi := &file_proto_education_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradesResponse) ProtoMessage() {}

func (x *GetGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradesResponse.ProtoReflect.Descriptor instead.
func (*GetGradesResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{12}
}

func (x *GetGradesResponse) GetGrades() []*GradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

type ScheduleTodayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTodayRequest) Reset() {
	*x = ScheduleTodayRequest{}
	mi := &file_proto_education_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTodayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTodayRequest) ProtoMessage() {}

func (x *ScheduleTodayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTodayRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTodayRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{13}
}

func (x *ScheduleTodayRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ScheduleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleItem) Reset() {
	*x = ScheduleItem{}
	mi := &file_proto_education_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleItem) ProtoMessage() {}

func (x *ScheduleItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleItem.ProtoReflect.Descriptor instead.
func (*ScheduleItem) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{14}
}

func (x *ScheduleItem) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ScheduleItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ScheduleItem) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ScheduleItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ScheduleTodayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScheduleItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTodayResponse) Reset() {
	*x = ScheduleTodayResponse{}
	mi := &file_proto_education_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTodayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTodayResponse) ProtoMessage() {}

func (x *ScheduleTodayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTodayResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTodayResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{15}
}

func (x *ScheduleTodayResponse) GetItems() []*ScheduleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SearchTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTeacherRequest) Reset() {
	*x = SearchTeacherRequest{}
	mi := &file_proto_education_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeacherRequest) ProtoMessage() {}

func (x *SearchTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeacherRequest.ProtoReflect.Descriptor instead.
func (*SearchTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{16}
}

func (x *SearchTeacherRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type TeacherItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Department    string                 `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherItem) Reset() {
	*x = TeacherItem{}
	mi := &file_proto_education_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherItem) ProtoMessage() {}

func (x *TeacherItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherItem.ProtoReflect.Descriptor instead.
func (*TeacherItem) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{17}
}

func (x *TeacherItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeacherItem) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *TeacherItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SearchTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*TeacherItem         `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTeacherResponse) Reset() {
	*x = SearchTeacherResponse{}
	mi := &file_proto_education_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTeacherResponse) ProtoMessage() {}

func (x *SearchTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTeacherResponse.ProtoReflect.Descriptor instead.
func (*SearchTeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{18}
}

func (x *SearchTeacherResponse) GetTeachers() []*TeacherItem {
	if x != nil {
		return x.Teachers
	}
	return nil
}

type CoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoursesRequest) Reset() {
	*x = CoursesRequest{}
	mi := &file_proto_education_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoursesRequest) ProtoMessage() {}

func (x *CoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoursesRequest.ProtoReflect.Descriptor instead.
func (*CoursesRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{19}
}

type CourseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	Teacher       string                 `protobuf:"bytes,4,opt,name=teacher,proto3" json:"teacher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseItem) Reset() {
	*x = CourseItem{}
	mi := &file_proto_education_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseItem) ProtoMessage() {}

func (x *CourseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseItem.ProtoReflect.Descriptor instead.
func (*CourseItem) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{20}
}

func (x *CourseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseItem) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *CourseItem) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

type CoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*CourseItem          `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoursesResponse) Reset() {
	*x = CoursesResponse{}
	mi := &file_proto_education_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoursesResponse) ProtoMessage() {}

func (x *CoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoursesResponse.ProtoReflect.Descriptor instead.
func (*CoursesResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{21}
}

func (x *CoursesResponse) GetCourses() []*CourseItem {
	if x != nil {
		return x.Courses
	}
	return nil
}

type AttendanceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceStatsRequest) Reset() {
	*x = AttendanceStatsRequest{}
	mi := &file_proto_education_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceStatsRequest) ProtoMessage() {}

func (x *AttendanceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceStatsRequest.ProtoReflect.Descriptor instead.
func (*AttendanceStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{22}
}

func (x *AttendanceStatsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type AttendanceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       float32                `protobuf:"fixed32,1,opt,name=percent,proto3" json:"percent,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Present       int32                  `protobuf:"varint,3,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceStatsResponse) Reset() {
	*x = AttendanceStatsResponse{}
	mi := &file_proto_education_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceStatsResponse) ProtoMessage() {}

func (x *AttendanceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceStatsResponse.ProtoReflect.Descriptor instead.
func (*AttendanceStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{23}
}

func (x *AttendanceStatsResponse) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *AttendanceStatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AttendanceStatsResponse) GetPresent() int32 {
	if x != nil {
		return x.Present
	}
	return 0
}

type OfficeHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfficeHoursRequest) Reset() {
	*x = OfficeHoursRequest{}
	mi := &file_proto_education_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficeHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeHoursRequest) ProtoMessage() {}

func (x *OfficeHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeHoursRequest.ProtoReflect.Descriptor instead.
func (*OfficeHoursRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{24}
}

func (x *OfficeHoursRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type OfficeHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         string                 `protobuf:"bytes,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfficeHoursResponse) Reset() {
	*x = OfficeHoursResponse{}
	mi := &file_proto_education_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfficeHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeHoursResponse) ProtoMessage() {}

func (x *OfficeHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeHoursResponse.ProtoReflect.Descriptor instead.
func (*OfficeHoursResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{25}
}

func (x *OfficeHoursResponse) GetHours() string {
	if x != nil {
		return x.Hours
	}
	return ""
}

func (x *OfficeHoursResponse) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type StudentProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentProfileRequest) Reset() {
	*x = StudentProfileRequest{}
	mi := &file_proto_education_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentProfileRequest) ProtoMessage() {}

func (x *StudentProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentProfileRequest.ProtoReflect.Descriptor instead.
func (*StudentProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{26}
}

func (x *StudentProfileRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type StudentProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Specialty     string                 `protobuf:"bytes,3,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentProfileResponse) Reset() {
	*x = StudentProfileResponse{}
	mi := &file_proto_education_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentProfileResponse) ProtoMessage() {}

func (x *StudentProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_education_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentProfileResponse.ProtoReflect.Descriptor instead.
func (*StudentProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_education_proto_rawDescGZIP(), []int{27}
}

func (x *StudentProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentProfileResponse) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *StudentProfileResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_proto_education_proto protoreflect.FileDescriptor

const file_proto_education_proto_rawDesc = "" +
	"\n" +
	"\x15proto/education.proto\x12\x05proto\"+\n" +
	"\n" +
	"GPARequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\x1f\n" +
	"\vGPAResponse\x12\x10\n" +
	"\x03gpa\x18\x01 \x01(\x02R\x03gpa\"\x7f\n" +
	"\x11AttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\".\n" +
	"\x12AttendanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"D\n" +
	"\x0eEnrollResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13ExamScheduleRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\";\n" +
	"\x14ExamScheduleResponse\x12#\n" +
	"\rschedule_json\x18\x01 \x01(\tR\fscheduleJson\"O\n" +
	"\x11DropCourseRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"H\n" +
	"\x12DropCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x10GetGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"O\n" +
	"\tGradeItem\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"=\n" +
	"\x11GetGradesResponse\x12(\n" +
	"\x06grades\x18\x01 \x03(\v2\x10.proto.GradeItemR\x06grades\"5\n" +
	"\x14ScheduleTodayRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"d\n" +
	"\fScheduleItem\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"B\n" +
	"\x15ScheduleTodayResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.proto.ScheduleItemR\x05items\",\n" +
	"\x14SearchTeacherRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"W\n" +
	"\vTeacherItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"department\x18\x02 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"G\n" +
	"\x15SearchTeacherResponse\x12.\n" +
	"\bteachers\x18\x01 \x03(\v2\x12.proto.TeacherItemR\bteachers\"\x10\n" +
	"\x0eCoursesRequest\"f\n" +
	"\n" +
	"CourseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\x12\x18\n" +
	"\ateacher\x18\x04 \x01(\tR\ateacher\">\n" +
	"\x0fCoursesResponse\x12+\n" +
	"\acourses\x18\x01 \x03(\v2\x11.proto.CourseItemR\acourses\"7\n" +
	"\x16AttendanceStatsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"c\n" +
	"\x17AttendanceStatsResponse\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x02R\apercent\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\apresent\x18\x03 \x01(\x05R\apresent\"3\n" +
	"\x12OfficeHoursRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\"?\n" +
	"\x13OfficeHoursResponse\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\tR\x05hours\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"6\n" +
	"\x15StudentProfileRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"t\n" +
	"\x16StudentProfileResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tspecialty\x18\x03 \x01(\tR\tspecialty\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year2\xf7\x06\n" +
	"\x10EducationService\x126\n" +
	"\rGetStudentGPA\x12\x11.proto.GPARequest\x1a\x12.proto.GPAResponse\x12G\n" +
	"\x10SubmitAttendance\x12\x18.proto.AttendanceRequest\x1a\x19.proto.AttendanceResponse\x12=\n" +
	"\x0eEnrollToCourse\x12\x14.proto.EnrollRequest\x1a\x15.proto.EnrollResponse\x12J\n" +
	"\x0fGetExamSchedule\x12\x1a.proto.ExamScheduleRequest\x1a\x1b.proto.ExamScheduleResponse\x12A\n" +
	"\n" +
	"DropCourse\x12\x18.proto.DropCourseRequest\x1a\x19.proto.DropCourseResponse\x12>\n" +
	"\tGetGrades\x12\x17.proto.GetGradesRequest\x1a\x18.proto.GetGradesResponse\x12M\n" +
	"\x10GetScheduleToday\x12\x1b.proto.ScheduleTodayRequest\x1a\x1c.proto.ScheduleTodayResponse\x12J\n" +
	"\rSearchTeacher\x12\x1b.proto.SearchTeacherRequest\x1a\x1c.proto.SearchTeacherResponse\x12B\n" +
	"\x11GetCoursesCatalog\x12\x15.proto.CoursesRequest\x1a\x16.proto.CoursesResponse\x12S\n" +
	"\x12GetAttendanceStats\x12\x1d.proto.AttendanceStatsRequest\x1a\x1e.proto.AttendanceStatsResponse\x12N\n" +
	"\x15GetTeacherOfficeHours\x12\x19.proto.OfficeHoursRequest\x1a\x1a.proto.OfficeHoursResponse\x12P\n" +
	"\x11GetStudentProfile\x12\x1c.proto.StudentProfileRequest\x1a\x1d.proto.StudentProfileResponseB\x15Z\x13aitu-superapp/protob\x06proto3"

var (
	file_proto_education_proto_rawDescOnce sync.Once
	file_proto_education_proto_rawDescData []byte
)

func file_proto_education_proto_rawDescGZIP() []byte {
	file_proto_education_proto_rawDescOnce.Do(func() {
		file_proto_education_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_education_proto_rawDesc), len(file_proto_education_proto_rawDesc)))
	})
	return file_proto_education_proto_rawDescData
}

var file_proto_education_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_education_proto_goTypes = []any{
	(*GPARequest)(nil),              // 0: proto.GPARequest
	(*GPAResponse)(nil),             // 1: proto.GPAResponse
	(*AttendanceRequest)(nil),       // 2: proto.AttendanceRequest
	(*AttendanceResponse)(nil),      // 3: proto.AttendanceResponse
	(*EnrollRequest)(nil),           // 4: proto.EnrollRequest
	(*EnrollResponse)(nil),          // 5: proto.EnrollResponse
	(*ExamScheduleRequest)(nil),     // 6: proto.ExamScheduleRequest
	(*ExamScheduleResponse)(nil),    // 7: proto.ExamScheduleResponse
	(*DropCourseRequest)(nil),       // 8: proto.DropCourseRequest
	(*DropCourseResponse)(nil),      // 9: proto.DropCourseResponse
	(*GetGradesRequest)(nil),        // 10: proto.GetGradesRequest
	(*GradeItem)(nil),               // 11: proto.GradeItem
	(*GetGradesResponse)(nil),       // 12: proto.GetGradesResponse
	(*ScheduleTodayRequest)(nil),    // 13: proto.ScheduleTodayRequest
	(*ScheduleItem)(nil),            // 14: proto.ScheduleItem
	(*ScheduleTodayResponse)(nil),   // 15: proto.ScheduleTodayResponse
	(*SearchTeacherRequest)(nil),    // 16: proto.SearchTeacherRequest
	(*TeacherItem)(nil),             // 17: proto.TeacherItem
	(*SearchTeacherResponse)(nil),   // 18: proto.SearchTeacherResponse
	(*CoursesRequest)(nil),          // 19: proto.CoursesRequest
	(*CourseItem)(nil),              // 20: proto.CourseItem
	(*CoursesResponse)(nil),         // 21: proto.CoursesResponse
	(*AttendanceStatsRequest)(nil),  // 22: proto.AttendanceStatsRequest
	(*AttendanceStatsResponse)(nil), // 23: proto.AttendanceStatsResponse
	(*OfficeHoursRequest)(nil),      // 24: proto.OfficeHoursRequest
	(*OfficeHoursResponse)(nil),     // 25: proto.OfficeHoursResponse
	(*StudentProfileRequest)(nil),   // 26: proto.StudentProfileRequest
	(*StudentProfileResponse)(nil),  // 27: proto.StudentProfileResponse
}
var file_proto_education_proto_depIdxs = []int32{
	11, // 0: proto.GetGradesResponse.grades:type_name -> proto.GradeItem
	14, // 1: proto.ScheduleTodayResponse.items:type_name -> proto.ScheduleItem
	17, // 2: proto.SearchTeacherResponse.teachers:type_name -> proto.TeacherItem
	20, // 3: proto.CoursesResponse.courses:type_name -> proto.CourseItem
	0,  // 4: proto.EducationService.GetStudentGPA:input_type -> proto.GPARequest
	2,  // 5: proto.EducationService.SubmitAttendance:input_type -> proto.AttendanceRequest
	4,  // 6: proto.EducationService.EnrollToCourse:input_type -> proto.EnrollRequest
	6,  // 7: proto.EducationService.GetExamSchedule:input_type -> proto.ExamScheduleRequest
	8,  // 8: proto.EducationService.DropCourse:input_type -> proto.DropCourseRequest
	10, // 9: proto.EducationService.GetGrades:input_type -> proto.GetGradesRequest
	13, // 10: proto.EducationService.GetScheduleToday:input_type -> proto.ScheduleTodayRequest
	16, // 11: proto.EducationService.SearchTeacher:input_type -> proto.SearchTeacherRequest
	19, // 12: proto.EducationService.GetCoursesCatalog:input_type -> proto.CoursesRequest
	22, // 13: proto.EducationService.GetAttendanceStats:input_type -> proto.AttendanceStatsRequest
	24, // 14: proto.EducationService.GetTeacherOfficeHours:input_type -> proto.OfficeHoursRequest
	26, // 15: proto.EducationService.GetStudentProfile:input_type -> proto.StudentProfileRequest
	1,  // 16: proto.EducationService.GetStudentGPA:output_type -> proto.GPAResponse
	3,  // 17: proto.EducationService.SubmitAttendance:output_type -> proto.AttendanceResponse
	5,  // 18: proto.EducationService.EnrollToCourse:output_type -> proto.EnrollResponse
	7,  // 19: proto.EducationService.GetExamSchedule:output_type -> proto.ExamScheduleResponse
	9,  // 20: proto.EducationService.DropCourse:output_type -> proto.DropCourseResponse
	12, // 21: proto.EducationService.GetGrades:output_type -> proto.GetGradesResponse
	15, // 22: proto.EducationService.GetScheduleToday:output_type -> proto.ScheduleTodayResponse
	18, // 23: proto.EducationService.SearchTeacher:output_type -> proto.SearchTeacherResponse
	21, // 24: proto.EducationService.GetCoursesCatalog:output_type -> proto.CoursesResponse
	23, // 25: proto.EducationService.GetAttendanceStats:output_type -> proto.AttendanceStatsResponse
	25, // 26: proto.EducationService.GetTeacherOfficeHours:output_type -> proto.OfficeHoursResponse
	27, // 27: proto.EducationService.GetStudentProfile:output_type -> proto.StudentProfileResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_education_proto_init() }
func file_proto_education_proto_init() {
	if File_proto_education_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_education_proto_rawDesc), len(file_proto_education_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_education_proto_goTypes,
		DependencyIndexes: file_proto_education_proto_depIdxs,
		MessageInfos:      file_proto_education_proto_msgTypes,
	}.Build()
	File_proto_education_proto = out.File
	file_proto_education_proto_goTypes = nil
	file_proto_education_proto_depIdxs = nil
}
